### ISSUE TITLE
[BUG] Pillar not worterlogged

### ISSUE THREAD

**Issue by zwibblTV** [Steven-Paw-Design/awesomeshop#13]
### Minecraft & AwesomeShop-Version:
1.5.0

### What is the Bug?:
Pillar not waterlogged

### Server or Clientside?:
Both

### If it crashes the game: Does it crash into Titlescreen or the enitre Game?:
No crash

### What did you do before that bug occured?:
Placed the pillar in water

### If possible, please paste a link to your crash-report and latest.log (for example on pastebin or hastebin):
No Crash-Report

### What Mods do you run with Awesome Shop together?:
https://www.technicpack.net/modpack/drugar-11.1830341

**Comment by StevenPaw** [comment]
Will be fixed in fbce8ec31967b6a9c4541b4890efcffa1f91a153
Probably in Update 1.5.1 it will work like a slab
