### ISSUE TITLE
[BUG] Wrong Piano Description

### ISSUE THREAD

**Issue by zwibblTV** [Steven-Paw-Design/awesomeshop#16]
### Minecraft & AwesomeShop-Version:
1.16.5 & 1.5.2

### What is the Bug?:
Piano has the Christmas Tree Description

### Server or Clientside?:
Both

### If it crashes the game: Does it crash into Titlescreen or the enitre Game?:
No Crash

### What did you do before that bug occured?:
Nothing

### If possible, please paste a link to your crash-report and latest.log (for example on pastebin or hastebin):
No Crash

### What Mods do you run with Awesome Shop together?:
https://www.technicpack.net/modpack/drugar-11

**Comment by StevenPaw** [comment]
Fixed in dc4fb6c53dbf00fbe4ab847829fe5b01a6297aea
